# Generated by Django 5.0.1 on 2024-01-10 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_alter_bookinstance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('r', 'Reserved'), ('m', 'Maintenance'), ('o', 'On loan'), ('a', 'Available')], default='m', help_text='Book availability', max_length=1),
        ),
    ]
