# Generated by Django 4.2.7 on 2024-01-29 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0038_alter_bookinstance_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'permissions': (('can_mark_returned', 'Set book as returned'),)},
        ),
        migrations.RenameField(
            model_name='book',
            old_name='genres',
            new_name='genre',
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('r', 'Reserved'), ('o', 'On loan'), ('m', 'Maintenance'), ('a', 'Available')], default='m', help_text='Book availability', max_length=1),
        ),
    ]
